#!/bin/sh -e
# Copyright (c) 2016 The crouton Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

USAGE="${0##*/} [-n] [URL]
Open an URL in Chromium OS.
Switches back to Chromium OS unless -n is specified."

. "`dirname "$0"`/../installer/functions"

noswitch=''
if [ "$1" = '-n' ]; then
    noswitch='y'
    shift
fi

if [ -z "$*" -o "$1" = '-h' -o "$1" = '--help' ]; then
    error 0 "$USAGE"
fi

host-dbus dbus-send --system \
  --type=method_call \
  --print-reply \
  --dest=org.chromium.UrlHandlerService \
  /org/chromium/UrlHandlerService \
  org.chromium.UrlHandlerServiceInterface.OpenUrl \
  "string:$*"

if [ -z "$noswitch" ]; then
    croutoncycle cros
fi
